"""slide not unique

Revision ID: 6188156e019d
Revises: 611e05946395
Create Date: 2025-02-15 13:12:05.813890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6188156e019d'
down_revision: Union[str, None] = '611e05946395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slides_request_id_key', 'slides', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('slides_request_id_key', 'slides', ['request_id'])
    # ### end Alembic commands ###
